<?php
/**
 * Backup copy of previous Admin Routes (with cache + expansion).
 * Preserved before migrating to parameterized routing.
 * Date: 2025-11-08
 */

namespace App\Modules\Admin\Routes;

use App\Modules\Admin\Controller;
use App\Modules\Admin\Model;

class Routesc
{
    private $model;
    private $table = 'user';
    private string $cacheFile;
    private int $cacheLifetime = 3600; // 1 hour

    public function __construct()
    {
        $this->cacheFile = __DIR__ . '/../../../etc/storage/cache/admin_routes.php';
    }

    public function routes($router)
    {
        $router->addRoute('/admin', Controller::class, 'display');
        $router->addRoute('/admin/users', Controller::class, 'display');
        $router->addRoute('/admin/users/add', Controller::class, 'display');

        if ($this->isCacheValid()) {
            $this->loadCachedRoutes($router);
        } else {
            $this->rebuildCache($router);
        }
    }

    private function isCacheValid(): bool
    {
        if (!file_exists($this->cacheFile)) {
            return false;
        }
        $cacheAge = time() - filemtime($this->cacheFile);
        if ($cacheAge >= $this->cacheLifetime) {
            return false;
        }
        return true;
    }

    private function loadCachedRoutes($router): void
    {
        $cachedRoutes = include $this->cacheFile;
        foreach ($cachedRoutes as $route) {
            $router->addRoute($route['path'], $route['controller'], $route['method']);
        }
    }

    private function rebuildCache($router): void
    {
        $this->model = new Model();
        $users = $this->model->getAllUsers();
        $userIds = [];
        foreach ($users as $user) {
            $userIds[] = $user['id'];
        }
        $cachedRoutes = [];
        foreach ($userIds as $userId) {
            $editRoute = [
                'path' => '/admin/users/edit/' . $userId,
                'controller' => Controller::class,
                'method' => 'display'
            ];
            $cachedRoutes[] = $editRoute;
            $router->addRoute($editRoute['path'], $editRoute['controller'], $editRoute['method']);
        }
        foreach ($userIds as $userId) {
            $deleteRoute = [
                'path' => '/admin/users/delete/' . $userId,
                'controller' => Controller::class,
                'method' => 'display'
            ];
            $cachedRoutes[] = $deleteRoute;
            $router->addRoute($deleteRoute['path'], $deleteRoute['controller'], $deleteRoute['method']);
        }
        $this->saveCache($cachedRoutes);
    }

    private function saveCache(array $routes): void
    {
        $cacheDir = dirname($this->cacheFile);
        if (!is_dir($cacheDir)) {
            mkdir($cacheDir, 0755, true);
        }
        $timestamp = date('Y-m-d H:i:s');
        $routeCount = count($routes);
        $content = <<<PHP
<?php
/**
 * Auto-generated Route Cache for Admin Module
 * Generated: {$timestamp}
 * Total Routes: {$routeCount}
 * DO NOT EDIT THIS FILE MANUALLY!
 */

return 
PHP;
        $content .= var_export($routes, true) . ";\n";
        file_put_contents($this->cacheFile, $content);
    }

    public static function clearCache(): void
    {
        $cacheFile = __DIR__ . '/../../../etc/storage/cache/admin_routes.php';
        if (file_exists($cacheFile)) {
            unlink($cacheFile);
        }
    }

    public static function getCacheStats(): array
    {
        $cacheFile = __DIR__ . '/../../../etc/storage/cache/admin_routes.php';
        if (!file_exists($cacheFile)) {
            return [
                'exists' => false,
                'age' => 0,
                'routes' => 0,
                'size' => 0,
                'created' => null
            ];
        }
        $routes = include $cacheFile;
        return [
            'exists' => true,
            'age' => time() - filemtime($cacheFile),
            'routes' => count($routes),
            'size' => filesize($cacheFile),
            'created' => date('Y-m-d H:i:s', filemtime($cacheFile))
        ];
    }
}











