<?php
/**
 * App\Modules\TestParent Module Configuration
 * Generated by Enhanced Module Generator
 */

return [
    'module' => [
        'name' => 'App\Modules\TestParent',
        'version' => '2.0-enhanced',
        'type' => 'basic',
        'generated_at' => '2025-11-15 21:01:13',
        'generator_version' => '2.0'
    ],
    
    'features' => [
        'auto_discovery' => true,
        'caching' => true,
        'middleware_ready' => true,
        'submodule_support' => true,
        'api_enabled' => false
    ],
    
    'routes' => [
        'base_route' => 'testparent',
        'namespace' => 'App\Modules\TestParent\\Routes',
        'auto_discovery_path' => 'routes/Routes.php'
    ],
    
    'database' => [
        'table_name' => 'testparents',
        'create_table' => false
    ],
    
    'environment' => [
        'respect_cache_settings' => true,
        'debug_mode_aware' => true,
        'production_optimized' => true
    ]
];